name: Offline Deployment Semantic Release

on:
  push:
    branches:
      - offline-deployment
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout offline-deployment
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: offline-deployment

      - name: Determine next semantic version
        id: version
        run: |
          # Get the latest tag, or empty if none
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            MAJOR=$(echo $LAST_TAG | cut -d. -f1 | tr -d 'v')
            MINOR=$(echo $LAST_TAG | cut -d. -f2)
            PATCH=$(echo $LAST_TAG | cut -d. -f3)
            RANGE="$LAST_TAG..HEAD"
          else
            MAJOR=1; MINOR=0; PATCH=0
            RANGE=""
          fi
      
          COMMITS=$(git log --pretty=format:"%H" $RANGE)
      
          BUMP="patch"
          for SHA in $COMMITS; do
            MSG=$(git log -1 --pretty=format:"%s" $SHA)
            if [[ "$MSG" =~ ^(ci|chore|docs): ]]; then
              continue
            fi
            if git diff-tree --no-commit-id --name-only -r $SHA | grep -vqE '\.ya?ml$|\.md$'; then
              if echo "$MSG" | grep -q -E 'BREAKING CHANGE|^feat!:'; then
                BUMP="major"
                break
              elif echo "$MSG" | grep -q -E '^feat:'; then
                BUMP="minor"
              elif echo "$MSG" | grep -q -E '^fix:' && [ "$BUMP" = "patch" ]; then
                BUMP="patch"
              fi
            fi
          done
      
          if [ "$BUMP" = "major" ]; then
            MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0
          elif [ "$BUMP" = "minor" ]; then
            MINOR=$((MINOR + 1)); PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Prepare clean dist directory for archiving
        run: |
          rm -rf dist
          mkdir dist
          rsync -a --exclude='.git' --exclude='node_modules' --exclude='dist' ./ dist/

      - name: Create offline build archives (ZIP and TAR.GZ) with version tag
        run: |
          cd dist
          BUILD_NAME="elecalculate-offline-${{ steps.version.outputs.new_tag }}"
          zip -r "../$BUILD_NAME.zip" .
          tar -czf "../$BUILD_NAME.tar.gz" .
          cd ..
          echo "ZIP_NAME=$BUILD_NAME.zip" >> $GITHUB_ENV
          echo "TAR_NAME=$BUILD_NAME.tar.gz" >> $GITHUB_ENV

      - name: Gather and format release notes
        id: notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            RANGE=""
          else
            RANGE="$LAST_TAG..HEAD"
          fi

          # Grouped release notes
          FEATURES=""
          FIXES=""
          OTHERS=""
          for SHA in $(git log --pretty=format:"%H" $RANGE); do
            MSG=$(git log -1 --pretty=format:"%s" $SHA)
            FILES=$(git diff-tree --no-commit-id --name-only -r $SHA)
            # Exclude infra/ci/docs and commits that only touch .yml/.yaml/.md
            if [[ "$MSG" =~ ^(ci|chore|docs): ]]; then
              continue
            fi
            ONLY_INFRA=true
            for FILE in $FILES; do
              if [[ ! "$FILE" =~ \.ya?ml$ && ! "$FILE" =~ \.md$ ]]; then
                ONLY_INFRA=false
                break
              fi
            done
            if $ONLY_INFRA; then
              continue
            fi
            if [[ "$MSG" =~ ^feat: ]]; then
              FEATURES+=$'\n'"* ${MSG#feat: }"
            elif [[ "$MSG" =~ ^fix: ]]; then
              FIXES+=$'\n'"* ${MSG#fix: }"
            else
              OTHERS+=$'\n'"* $MSG"
            fi
          done

          {
            echo "**Build date:** $(date -u +"%Y-%m-%d %H:%M UTC")"
            echo "**Branch:** offline-deployment"
            echo "**Assets:** ${{ env.ZIP_NAME }}, ${{ env.TAR_NAME }}"
            echo
            if [ -n "$FEATURES" ]; then
              echo "### Features"
              echo "$FEATURES"
              echo
            fi
            if [ -n "$FIXES" ]; then
              echo "### Fixes"
              echo "$FIXES"
              echo
            fi
            if [ -n "$OTHERS" ]; then
              echo "### Other changes"
              echo "$OTHERS"
              echo
            fi
          } > release-notes.md

          echo >> release-notes.md
          {
            echo "release_notes<<EOF"
            cat release-notes.md
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git tag ${{ steps.version.outputs.new_tag }}
          git push origin ${{ steps.version.outputs.new_tag }}

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          target_commitish: offline-deployment
          name: Release ${{ steps.version.outputs.new_tag }}
          body: ${{ steps.notes.outputs.release_notes }}
          files: |
            ${{ env.ZIP_NAME }}
            ${{ env.TAR_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
